#!/bin/bash

curl -v --data-urlencode "auth_user=$1" --data-urlencode "auth_pass=$2" \
 --data-urlencode "accept=Accept" --data-urlencode "redirurl=http://www.google.com/" \
https://captiveportal.provinciawifi.it:8001/

#http://localhost/provinciawifi/
